### ISSUE TITLE
Players are not unmuted

### ISSUE THREAD

**Issue by Lennart-1337** [deluvas1911/saltychat-altv#2] opened 2021-03-05 17:20 UTC
**Version**
1.0.4

**Describe the bug**
Players are not unmuted to others (The other player hears the person). This phenomenon occurs randomly and can only be reproduced by chance.

**Usage of the code**
Just alt.emit("SaltyChat:EnablePlayer", player)

**To Reproduce**
1. Just try

**Expected behavior**
You should be able to hear other players

**Comment by deluvas1911** [comment] 2021-03-06 18:34
Haven't managed yet reproducing it. Can you manage somehow to reproduce it and provide SaltyChat extensive logs?

**Comment by Letsion** [comment] 2021-03-09 18:50
@deluvas1911 I think he can not 😅

**Comment by LorianAtashi01** [comment] 2021-03-11 22:17
gonna close the issue because the creator of the issue is not answering anymore

**Closed as completed by LorianAtashi01** 2021-03-11 22:17 UTC
